networks:
  deweylearn:
    external: true
      

services:
  r2r:
    image: deweylearn-r2r
    container_name: DeweyLearnR2R
    ports:
      - "9311:9311"
    environment:
      - PYTHONUNBUFFERED=1
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DBNAME=${POSTGRES_DBNAME}
      - POSTGRES_VECS_COLLECTION=${POSTGRES_VECS_COLLECTION}
    networks:
      - deweylearn
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:9311/v1/health"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 5
    restart: always
    volumes:
      - /home/deweylearn/DEV/DeweyLearnK12/data:/app/data
