name: Deploy Docker on Release

on:
  release:
    types: [created]
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Release tag name'
        required: true
        default: 'latest' # Provide a default value if needed

jobs:
  build-and-push-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      
      - name: Docker Auth
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      
      - name: Google Auth
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'
  
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'
  
      - name: 'Use gcloud CLI'
        run: 'gcloud info'

      - name: Configure Docker to use Google Cloud Artifact Registry
        run: gcloud auth configure-docker us-east1-docker.pkg.dev

      # Determine Tag Name based on trigger event
      - name: Set Dynamic Tag Name
        id: set_tag
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "::set-output name=TAG_NAME::${{ github.event.inputs.tag_name }}"
          else
            echo "::set-output name=TAG_NAME::${{ github.event.release.tag_name }}"
          fi

      # Publish images
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            emrgntcmplxty/r2r:latest
            emrgntcmplxty/r2r:${{ steps.set_tag.outputs.TAG_NAME }}
            us-east1-docker.pkg.dev/alert-rush-397022/sciphi-r2r/r2r:latest
            us-east1-docker.pkg.dev/alert-rush-397022/sciphi-r2r/r2r:${{ steps.set_tag.outputs.TAG_NAME }}
          platforms: linux/amd64,linux/arm64
